#ifndef PROVIDERS_CONSTEVALOPERATIONGROUPPROVIDERCONFIG_H_INCLUDED
#define PROVIDERS_CONSTEVALOPERATIONGROUPPROVIDERCONFIG_H_INCLUDED

namespace Mod
{
	struct ConstEvalOperationGroupProviderConfig
	{

	};
}

#endif