#ifndef PROVIDERS_MODELCMPTRAWDATAIMPORTERPROVIDERCONFIG_H_INCLUDED
#define PROVIDERS_MODELCMPTRAWDATAIMPORTERPROVIDERCONFIG_H_INCLUDED

namespace Mod
{
	struct ModelCmptRawDataImporterProviderConfig
	{
		
	};
}

#endif