#ifndef D3D10DRV_FORW_H_INCLUDED
#define D3D10DRV_FORW_H_INCLUDED

namespace Mod
{
	#include "DefDeclareClass.h"

	MOD_DECLARE_BOLD_CLASS(D3D10FormatMap)
	MOD_DECLARE_BOLD_CLASS(D3D10UsageMap)
	MOD_DECLARE_BOLD_CLASS(D3D10Device)
	MOD_DECLARE_BOLD_CLASS(D3D10SRView)
	MOD_DECLARE_BOLD_CLASS(D3D10EffectIncludes)
	
	#include "UndefDeclareClass.h"	

	const DXGI_FORMAT D3D10_DISPLAY_FORMAT = DXGI_FORMAT_R8G8B8A8_UNORM;
}

#endif