#define MAX_SUCCESSOR_LENGTH	1				// Maximum number of symbols in a successor
#define MAX_SUCCESSOR_NUMBER	1				// Maximum number of rules with the same predecessor


//********************************
// Rule IDs
//********************************

#define SYMBOL_S1_RULE_1_ID		(SYMBOL_S1 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S10_RULE_1_ID		(SYMBOL_S10 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S11_RULE_1_ID		(SYMBOL_S11 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S12_RULE_1_ID		(SYMBOL_S12 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S13_RULE_1_ID		(SYMBOL_S13 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S14_RULE_1_ID		(SYMBOL_S14 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S15_RULE_1_ID		(SYMBOL_S15 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S16_RULE_1_ID		(SYMBOL_S16 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S17_RULE_1_ID		(SYMBOL_S17 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S18_RULE_1_ID		(SYMBOL_S18 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S19_RULE_1_ID		(SYMBOL_S19 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S2_RULE_1_ID		(SYMBOL_S2 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S20_RULE_1_ID		(SYMBOL_S20 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S21_RULE_1_ID		(SYMBOL_S21 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S22_RULE_1_ID		(SYMBOL_S22 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S23_RULE_1_ID		(SYMBOL_S23 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S24_RULE_1_ID		(SYMBOL_S24 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S25_RULE_1_ID		(SYMBOL_S25 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S26_RULE_1_ID		(SYMBOL_S26 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S27_RULE_1_ID		(SYMBOL_S27 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S28_RULE_1_ID		(SYMBOL_S28 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S29_RULE_1_ID		(SYMBOL_S29 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S3_RULE_1_ID		(SYMBOL_S3 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S30_RULE_1_ID		(SYMBOL_S30 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S31_RULE_1_ID		(SYMBOL_S31 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S32_RULE_1_ID		(SYMBOL_S32 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S33_RULE_1_ID		(SYMBOL_S33 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S34_RULE_1_ID		(SYMBOL_S34 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S35_RULE_1_ID		(SYMBOL_S35 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S36_RULE_1_ID		(SYMBOL_S36 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S37_RULE_1_ID		(SYMBOL_S37 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S38_RULE_1_ID		(SYMBOL_S38 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S39_RULE_1_ID		(SYMBOL_S39 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S4_RULE_1_ID		(SYMBOL_S4 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S40_RULE_1_ID		(SYMBOL_S40 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S41_RULE_1_ID		(SYMBOL_S41 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S42_RULE_1_ID		(SYMBOL_S42 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S43_RULE_1_ID		(SYMBOL_S43 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S44_RULE_1_ID		(SYMBOL_S44 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S45_RULE_1_ID		(SYMBOL_S45 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S46_RULE_1_ID		(SYMBOL_S46 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S47_RULE_1_ID		(SYMBOL_S47 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S48_RULE_1_ID		(SYMBOL_S48 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S49_RULE_1_ID		(SYMBOL_S49 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S5_RULE_1_ID		(SYMBOL_S5 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S50_RULE_1_ID		(SYMBOL_S50 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S6_RULE_1_ID		(SYMBOL_S6 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S7_RULE_1_ID		(SYMBOL_S7 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S8_RULE_1_ID		(SYMBOL_S8 * MAX_SUCCESSOR_NUMBER + 1)

#define SYMBOL_S9_RULE_1_ID		(SYMBOL_S9 * MAX_SUCCESSOR_NUMBER + 1)


//********************************
// Rule Lengths
//********************************

#define SYMBOL_S1_RULE_1_LENGTH	1

#define SYMBOL_S10_RULE_1_LENGTH	1

#define SYMBOL_S11_RULE_1_LENGTH	1

#define SYMBOL_S12_RULE_1_LENGTH	1

#define SYMBOL_S13_RULE_1_LENGTH	1

#define SYMBOL_S14_RULE_1_LENGTH	1

#define SYMBOL_S15_RULE_1_LENGTH	1

#define SYMBOL_S16_RULE_1_LENGTH	1

#define SYMBOL_S17_RULE_1_LENGTH	1

#define SYMBOL_S18_RULE_1_LENGTH	1

#define SYMBOL_S19_RULE_1_LENGTH	1

#define SYMBOL_S2_RULE_1_LENGTH	1

#define SYMBOL_S20_RULE_1_LENGTH	1

#define SYMBOL_S21_RULE_1_LENGTH	1

#define SYMBOL_S22_RULE_1_LENGTH	1

#define SYMBOL_S23_RULE_1_LENGTH	1

#define SYMBOL_S24_RULE_1_LENGTH	1

#define SYMBOL_S25_RULE_1_LENGTH	1

#define SYMBOL_S26_RULE_1_LENGTH	1

#define SYMBOL_S27_RULE_1_LENGTH	1

#define SYMBOL_S28_RULE_1_LENGTH	1

#define SYMBOL_S29_RULE_1_LENGTH	1

#define SYMBOL_S3_RULE_1_LENGTH	1

#define SYMBOL_S30_RULE_1_LENGTH	1

#define SYMBOL_S31_RULE_1_LENGTH	1

#define SYMBOL_S32_RULE_1_LENGTH	1

#define SYMBOL_S33_RULE_1_LENGTH	1

#define SYMBOL_S34_RULE_1_LENGTH	1

#define SYMBOL_S35_RULE_1_LENGTH	1

#define SYMBOL_S36_RULE_1_LENGTH	1

#define SYMBOL_S37_RULE_1_LENGTH	1

#define SYMBOL_S38_RULE_1_LENGTH	1

#define SYMBOL_S39_RULE_1_LENGTH	1

#define SYMBOL_S4_RULE_1_LENGTH	1

#define SYMBOL_S40_RULE_1_LENGTH	1

#define SYMBOL_S41_RULE_1_LENGTH	1

#define SYMBOL_S42_RULE_1_LENGTH	1

#define SYMBOL_S43_RULE_1_LENGTH	1

#define SYMBOL_S44_RULE_1_LENGTH	1

#define SYMBOL_S45_RULE_1_LENGTH	1

#define SYMBOL_S46_RULE_1_LENGTH	1

#define SYMBOL_S47_RULE_1_LENGTH	1

#define SYMBOL_S48_RULE_1_LENGTH	1

#define SYMBOL_S49_RULE_1_LENGTH	1

#define SYMBOL_S5_RULE_1_LENGTH	1

#define SYMBOL_S50_RULE_1_LENGTH	1

#define SYMBOL_S6_RULE_1_LENGTH	1

#define SYMBOL_S7_RULE_1_LENGTH	1

#define SYMBOL_S8_RULE_1_LENGTH	1

#define SYMBOL_S9_RULE_1_LENGTH	1


