# TileBasedShadows Makefile
# Nikita Kindt - 27th Feb. 2015
# Demo tested on Mint, Antergos and Gentoo

.PHONY: all rebuild clean
all:
	cd src && $(MAKE) TileBasedShadows

rebuild:
	cd src && $(MAKE) rebuild

clean:
	cd src && $(MAKE) clean
